/* This file was automatically generated by CasADi 3.6.6.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) drone_non_linear_ode_impl_dae_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[61] = {12, 12, 0, 0, 0, 0, 8, 16, 18, 23, 28, 33, 36, 41, 46, 0, 1, 2, 3, 4, 5, 7, 8, 0, 1, 2, 3, 5, 6, 7, 8, 0, 1, 0, 1, 2, 7, 8, 0, 1, 2, 6, 8, 0, 1, 2, 6, 7, 3, 7, 8, 3, 4, 5, 6, 8, 3, 4, 5, 6, 7};
static const casadi_int casadi_s4[27] = {12, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s5[15] = {12, 4, 0, 2, 4, 6, 8, 8, 9, 8, 10, 8, 9, 8, 10};
static const casadi_int casadi_s6[3] = {12, 0, 0};

/* drone_non_linear_ode_impl_dae_jac_x_xdot_u_z:(i0[12],i1[12],i2[4],i3[],i4[],i5[])->(o0[12x12,46nz],o1[12x12,12nz],o2[12x4,8nz],o3[12x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][8] : 0;
  a1=arg[0]? arg[0][5] : 0;
  a2=sin(a1);
  a3=arg[0]? arg[0][3] : 0;
  a4=cos(a3);
  a5=(a2*a4);
  a6=arg[0]? arg[0][4] : 0;
  a7=sin(a6);
  a1=cos(a1);
  a3=sin(a3);
  a8=(a1*a3);
  a9=(a7*a8);
  a9=(a5-a9);
  a9=(a0*a9);
  a10=arg[0]? arg[0][7] : 0;
  a11=(a2*a3);
  a12=(a1*a4);
  a13=(a7*a12);
  a13=(a11+a13);
  a13=(a10*a13);
  a9=(a9+a13);
  a9=(-a9);
  if (res[0]!=0) res[0][0]=a9;
  a5=(a7*a5);
  a5=(a5-a8);
  a5=(a10*a5);
  a11=(a7*a11);
  a12=(a12+a11);
  a12=(a0*a12);
  a5=(a5-a12);
  a5=(-a5);
  if (res[0]!=0) res[0][1]=a5;
  a5=cos(a6);
  a12=(a5*a4);
  a11=(a10*a12);
  a9=(a5*a3);
  a13=(a0*a9);
  a11=(a11-a13);
  a11=(-a11);
  if (res[0]!=0) res[0][2]=a11;
  a11=arg[0]? arg[0][10] : 0;
  a6=tan(a6);
  a13=(a6*a4);
  a13=(a11*a13);
  a14=arg[0]? arg[0][11] : 0;
  a15=(a6*a3);
  a15=(a14*a15);
  a13=(a13-a15);
  a13=(-a13);
  if (res[0]!=0) res[0][3]=a13;
  a13=(a11*a3);
  a15=(a14*a4);
  a13=(a13+a15);
  if (res[0]!=0) res[0][4]=a13;
  a13=(a4/a5);
  a15=(a11*a13);
  a16=(a3/a5);
  a17=(a14*a16);
  a15=(a15-a17);
  a15=(-a15);
  if (res[0]!=0) res[0][5]=a15;
  a15=9.8100000000000005e+00;
  a12=(a15*a12);
  a12=(-a12);
  if (res[0]!=0) res[0][6]=a12;
  a12=(a15*a9);
  if (res[0]!=0) res[0][7]=a12;
  a12=(a4*a1);
  a17=(a12*a5);
  a17=(a0*a17);
  a18=(a8*a5);
  a18=(a10*a18);
  a17=(a17+a18);
  a18=arg[0]? arg[0][6] : 0;
  a19=(a1*a7);
  a19=(a18*a19);
  a17=(a17-a19);
  a17=(-a17);
  if (res[0]!=0) res[0][8]=a17;
  a17=(a3*a2);
  a20=(a17*a5);
  a20=(a10*a20);
  a21=(a4*a2);
  a22=(a21*a5);
  a22=(a0*a22);
  a20=(a20+a22);
  a20=(a20-a19);
  a20=(-a20);
  if (res[0]!=0) res[0][9]=a20;
  a20=(a4*a7);
  a19=(a0*a20);
  a22=(a18*a5);
  a19=(a19+a22);
  a22=(a3*a7);
  a23=(a10*a22);
  a19=(a19+a23);
  if (res[0]!=0) res[0][10]=a19;
  a19=casadi_sq(a5);
  a23=(a4/a19);
  a23=(a14*a23);
  a19=(a3/a19);
  a19=(a11*a19);
  a23=(a23+a19);
  a23=(-a23);
  if (res[0]!=0) res[0][11]=a23;
  a23=(a13/a5);
  a23=(a23*a7);
  a23=(a14*a23);
  a19=(a16/a5);
  a19=(a19*a7);
  a19=(a11*a19);
  a23=(a23+a19);
  a23=(-a23);
  if (res[0]!=0) res[0][12]=a23;
  a23=(a15*a5);
  if (res[0]!=0) res[0][13]=a23;
  a22=(a15*a22);
  if (res[0]!=0) res[0][14]=a22;
  a15=(a15*a20);
  if (res[0]!=0) res[0][15]=a15;
  a15=(a3*a1);
  a20=(a7*a21);
  a20=(a15-a20);
  a20=(a0*a20);
  a22=(a7*a17);
  a22=(a12+a22);
  a22=(a10*a22);
  a20=(a20-a22);
  a2=(a5*a2);
  a2=(a18*a2);
  a20=(a20-a2);
  a20=(-a20);
  if (res[0]!=0) res[0][16]=a20;
  a15=(a7*a15);
  a15=(a15-a21);
  a15=(a10*a15);
  a20=(a7*a12);
  a20=(a17+a20);
  a20=(a0*a20);
  a15=(a15+a20);
  a15=(a15-a2);
  a15=(-a15);
  if (res[0]!=0) res[0][17]=a15;
  a15=(a1*a5);
  a15=(-a15);
  if (res[0]!=0) res[0][18]=a15;
  a1=(a5*a1);
  a1=(-a1);
  if (res[0]!=0) res[0][19]=a1;
  if (res[0]!=0) res[0][20]=a7;
  if (res[0]!=0) res[0][21]=a14;
  a1=(-a11);
  if (res[0]!=0) res[0][22]=a1;
  a1=(a8*a7);
  a1=(a21-a1);
  if (res[0]!=0) res[0][23]=a1;
  a1=(a17*a7);
  a1=(a12+a1);
  a1=(-a1);
  if (res[0]!=0) res[0][24]=a1;
  a9=(-a9);
  if (res[0]!=0) res[0][25]=a9;
  a14=(-a14);
  if (res[0]!=0) res[0][26]=a14;
  a14=arg[0]? arg[0][9] : 0;
  if (res[0]!=0) res[0][27]=a14;
  a12=(a12*a7);
  a17=(a17+a12);
  a17=(-a17);
  if (res[0]!=0) res[0][28]=a17;
  a21=(a21*a7);
  a8=(a8-a21);
  if (res[0]!=0) res[0][29]=a8;
  a5=(a4*a5);
  a5=(-a5);
  if (res[0]!=0) res[0][30]=a5;
  if (res[0]!=0) res[0][31]=a11;
  a14=(-a14);
  if (res[0]!=0) res[0][32]=a14;
  a14=-1.;
  if (res[0]!=0) res[0][33]=a14;
  a14=(-a0);
  if (res[0]!=0) res[0][34]=a14;
  if (res[0]!=0) res[0][35]=a10;
  a14=(a3*a6);
  a14=(-a14);
  if (res[0]!=0) res[0][36]=a14;
  a14=(-a4);
  if (res[0]!=0) res[0][37]=a14;
  a16=(-a16);
  if (res[0]!=0) res[0][38]=a16;
  if (res[0]!=0) res[0][39]=a0;
  a0=(-a18);
  if (res[0]!=0) res[0][40]=a0;
  a4=(a4*a6);
  a4=(-a4);
  if (res[0]!=0) res[0][41]=a4;
  if (res[0]!=0) res[0][42]=a3;
  a13=(-a13);
  if (res[0]!=0) res[0][43]=a13;
  a10=(-a10);
  if (res[0]!=0) res[0][44]=a10;
  if (res[0]!=0) res[0][45]=a18;
  a18=1.;
  if (res[1]!=0) res[1][0]=a18;
  if (res[1]!=0) res[1][1]=a18;
  if (res[1]!=0) res[1][2]=a18;
  if (res[1]!=0) res[1][3]=a18;
  if (res[1]!=0) res[1][4]=a18;
  if (res[1]!=0) res[1][5]=a18;
  if (res[1]!=0) res[1][6]=a18;
  if (res[1]!=0) res[1][7]=a18;
  if (res[1]!=0) res[1][8]=a18;
  if (res[1]!=0) res[1][9]=a18;
  if (res[1]!=0) res[1][10]=a18;
  if (res[1]!=0) res[1][11]=a18;
  a18=3.7037037037037038e+01;
  a10=arg[2]? arg[2][0] : 0;
  a10=(a10+a10);
  a13=(a18*a10);
  if (res[2]!=0) res[2][0]=a13;
  a13=1000.;
  a3=1.0000000000000001e-01;
  a10=(a3*a10);
  a10=(a13*a10);
  if (res[2]!=0) res[2][1]=a10;
  a10=arg[2]? arg[2][1] : 0;
  a10=(a10+a10);
  a4=(a18*a10);
  if (res[2]!=0) res[2][2]=a4;
  a10=(a3*a10);
  a10=(a13*a10);
  if (res[2]!=0) res[2][3]=a10;
  a10=arg[2]? arg[2][2] : 0;
  a10=(a10+a10);
  a4=(a18*a10);
  if (res[2]!=0) res[2][4]=a4;
  a10=(a3*a10);
  a10=(a13*a10);
  a10=(-a10);
  if (res[2]!=0) res[2][5]=a10;
  a10=arg[2]? arg[2][3] : 0;
  a10=(a10+a10);
  a18=(a18*a10);
  if (res[2]!=0) res[2][6]=a18;
  a3=(a3*a10);
  a13=(a13*a3);
  a13=(-a13);
  if (res[2]!=0) res[2][7]=a13;
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_non_linear_ode_impl_dae_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int drone_non_linear_ode_impl_dae_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_non_linear_ode_impl_dae_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_non_linear_ode_impl_dae_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int drone_non_linear_ode_impl_dae_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void drone_non_linear_ode_impl_dae_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void drone_non_linear_ode_impl_dae_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void drone_non_linear_ode_impl_dae_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int drone_non_linear_ode_impl_dae_jac_x_xdot_u_z_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int drone_non_linear_ode_impl_dae_jac_x_xdot_u_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real drone_non_linear_ode_impl_dae_jac_x_xdot_u_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_non_linear_ode_impl_dae_jac_x_xdot_u_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* drone_non_linear_ode_impl_dae_jac_x_xdot_u_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_non_linear_ode_impl_dae_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s2;
    case 5: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* drone_non_linear_ode_impl_dae_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int drone_non_linear_ode_impl_dae_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int drone_non_linear_ode_impl_dae_jac_x_xdot_u_z_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
