FROM osrf/ros:noetic-desktop-full

# Install dependencies, including NVIDIA packages, and clean up
RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
    curl \
    gnupg2 \
    lsb-release \
    x11-apps \
    libgl1-mesa-glx \
    libgl1-mesa-dri \
    libegl1-mesa \
    libglu1-mesa \
    libx11-dev \
    libxrandr-dev \
    libxext-dev \
    zsh \
    git && \
    rm -rf /var/lib/apt/lists/*

# Add NVIDIA's repository for the container toolkit (for Ubuntu 20.04)
RUN curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg && \
    curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
    sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
    tee /etc/apt/sources.list.d/nvidia-container-toolkit.list

# Update apt and install NVIDIA container toolkit and libraries
RUN apt-get update && apt-get install -y --no-install-recommends \
    nvidia-container-toolkit && \
    rm -rf /var/lib/apt/lists/*
    
# Add ROS repositories
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list' && \
    wget http://packages.ros.org/ros.key -O - | apt-key add -

# Install Catkin Tools
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-catkin-tools && \
    rm -rf /var/lib/apt/lists/*

# Set environment variables for ROS and Catkin
ENV ROS_DISTRO=noetic   
    


# Install additional ROS packages for Gazebo, RViz, and more
RUN apt-get update && apt-get install -y \
    ros-noetic-gazebo-ros-pkgs \
    ros-noetic-rviz \
    ros-noetic-rosbridge-suite \
    ros-noetic-ros-control \
    ros-noetic-ros-controllers && \
    rm -rf /var/lib/apt/lists/*
    
# Install Python dependencies required for pymavlink
RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-setuptools && \
    pip3 install future && \
    pip install pymavlink


    
# Install additional dependencies for non-Catkin packages
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    protobuf-compiler \
    libgoogle-glog-dev && \
    rm -rf /var/lib/apt/lists/*

# Install Oh My Zsh for a better shell experience
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" || true

# Ensure OpenGL uses the NVIDIA libraries instead of Mesa
ENV LIBGL_ALWAYS_INDIRECT=1
ENV __GLX_VENDOR_LIBRARY_NAME=nvidia

# Set environment variables for GPU usage and Gazebo
ENV QT_X11_NO_MITSHM=1
ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
ENV NVIDIA_REQUIRE_CUDA="cuda>=11.0"

# Set up the entrypoint for ROS environment
ENTRYPOINT ["/ros_entrypoint.sh"]

# Set ROS environment variables
SHELL ["/bin/bash", "-c"]

# Default shell command
CMD ["/bin/zsh"]

